version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'

    extra_hosts:
      - 'host.docker.internal:host-gateway'

    environment:
      - VITE_APP_BASE_URL=http://192.168.3.5:8082
      - NODE_ENV=development
